# Generated by Django 4.1.3 on 2022-12-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='computer',
        ),
        migrations.AddField(
            model_name='order',
            name='computer',
            field=models.ManyToManyField(related_name='orders', to='booking.computer'),
        ),
    ]
