# Generated by Django 4.1.3 on 2022-12-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_order_computer_order_computer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='computer',
            new_name='computers',
        ),
    ]
