# Generated by Django 4.1.3 on 2022-12-03 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_computerroom_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerroom',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='booking.computerroom', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='order',
            name='computers',
            field=models.ManyToManyField(related_name='orders', to='booking.computer', verbose_name='Компьютеры'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='RateComputerRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_hour', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена (час)')),
                ('three_hours', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена (3 часа)')),
                ('five_hours', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена (5 часов)')),
                ('seven_hours', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена (7 часов)')),
                ('night', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена (22:00 - 18:00)')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='booking.computerroom')),
            ],
        ),
    ]
